### ISSUE TITLE
Selection of multi platform .Net Core serial port library

### ISSUE THREAD

**Issue by dekiland** [erpnet/ErpNet.FP#1]
We must select **multi platform** .net core serial port library, which will be used as standard underlying communication with Fiscal Printers and Devices. This is team task, so I assigned this task to all of us. Please consider that there are not so many packed as NuGet packages, as well as we must select the **library with minimal dependencies and maximum portability**.
**Without this** library we will be forced to use only Microsoft Windows **System.IO.Ports**, which is not supported in .Net Core, **and stick only with Windows** :(

**Comment by dilyanrusev** [comment]
Quick search resulted in https://www.nuget.org/packages/Mono.Posix.NETStandard/1.0.0-beta2 - https://github.com/mono/mono/tree/master/mcs/class/Mono.Posix

**Comment by dilyanrusev** [comment]
Using mono POSIX, etc, we can take the idea from https://github.com/node-serialport/node-serialport/tree/master/packages/binding-abstract and https://github.com/node-serialport/node-serialport/tree/master/packages/bindings and do the work ourselves. Or, we could take the easy route and use the drivers provided by the Fiscal printer drivers. Some of them are in node and therefore work on linux.

**Comment by dekiland** [comment]
Mono.Posix.NETStandard, does not implement System.IO.Ports, consider this: https://www.nuget.org/packages/MonoSerialPort/   (.NETStandard 2.0)

**Comment by dilyanrusev** [comment]
Looks like somebody's already done the work for us. Looks great!

**Comment by dekiland** [comment]
Ok, so issue is considered closed then.
