### ISSUE TITLE
Improve reliability

### ISSUE THREAD

**Issue by valeriterziev** [erpnet/ErpNet.FP#102]
_Information about any given task is currently kept in memory for 20 minutes. After this, there is no way to know if a print job was successful._

There are cases when software (web based) cannot receive information about finished task in 20 minutes. Which lead to differences between software and fiscal device.
A customer with 70 workplaces with COM devices have around 10 such cases per month.
We are afraid this can cause software delist from NRA.

How can this be improved?

Two possible ideas:

1. **Keeping finished tasks in file on drive**, where they can stay 1 day. 
If need to keep file smaller, records can be removed when task information is requested

2. **Give info for the last transaction**. 
This will work great in cases where one device is used by one workplace.

**Comment by g-vvv** [comment]
It is out of the scope of the library. Keeping tracks of payments is your software responsibility. There is also an electronic journal in the fiscal device.
