### ISSUE TITLE
Monthly report / fiscal memory report

### ISSUE THREAD

**Issue by f1mp3r** [erpnet/ErpNet.FP#103]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a way to print monthly reports (or fiscal memory report by date) since it's required by the law. I know there is a way to print one out currently using the raw request API but a dedicated endpoint sounds reasonable.

**Comment by g-vvv** [comment]
They are not required by Law. See attached file: https://www.kik-info.com/forum/index.php?action=dlattach;topic=25363.0;attach=7460

**Comment by g-vvv** [comment]
Until you do not have a new device, "the one with automatic reports", you can use the fiscal device software provided by the manifacturer, or use a raw requests.
