### ISSUE TITLE
v.1.0.1002.2040 x64 (ZIP) error

### ISSUE THREAD

**Issue by dsetekh** [erpnet/ErpNet.FP#109]
v.1.0.1002.2040 x64

Failed to load the dll from [E:\erpnetlast\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from E:\erpnetlast\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306

v.1.0.926.1900 x64 is working fine
Microsoft Visual C++ 2015 Redistributable Update 3 (x64) is installed

v.1.0.1002.2040 x86 is also working fine

Can you, please, help with some ideas what may be the issue.

Thanks.

**Comment by g-vvv** [comment]
Just follow the link: https://go.microsoft.com/fwlink/?linkid=798306
