### ISSUE TITLE
Problem with reversalreceipt

### ISSUE THREAD

**Issue by StoyanMalchev** [erpnet/ErpNet.FP#114]
On DATECS WP-50X
Response contains
"ok":true
but nothing is printed on ECR
No such problem with TREMOL S21

[debug.log](https://github.com/erpnet/ErpNet.FP/files/3711797/debug.log)
[data.txt](https://github.com/erpnet/ErpNet.FP/files/3711812/data.txt)
[Responce.txt](https://github.com/erpnet/ErpNet.FP/files/3711813/Responce.txt)

**Comment by g-vvv** [comment]
There is extra space after the date in this field: "receiptDateTime":"2019-10-10T11:01:30 "
It should be: "receiptDateTime":"2019-10-10T11:01:30"
