### ISSUE TITLE
Datecs FP-650 `DeviceInfo`

### ISSUE THREAD

**Issue by wqweto** [erpnet/ErpNet.FP#115]
JFYI, in `BgDatecsPIslFiscalPrinterDriver.cs` the `DeviceInfo`'s members [`CommentTextMaxLength` and `ItemTextMaxLength`](https://github.com/erpnet/ErpNet.FP/blob/master/ErpNet.FP.Core/Drivers/BgDatecs/BgDatecsPIslFiscalPrinterDriver.cs#L60-L61) are off by 2 for FP-650 and probably the rest of the (lagacy) FP line.

[FP-650 product description](http://www.datecs.bg/bg/products/304) says `Име на артикул - До 36 символа` but anything above 34 bombs with a syntax error while the comment is silently trimmed at 40 symbols.

**Comment by g-vvv** [comment]
So there is again one of Datecs "hidden" features :) Thanks, I will fix it.

**Comment by g-vvv** [comment]
I will try with the FP-2000, if the issue apears there also.

**Comment by g-vvv** [comment]
New binaries published
