### ISSUE TITLE
Simplify manually adding printers

### ISSUE THREAD

**Issue by i-argentinski** [erpnet/ErpNet.FP#117]
In the dialog for adding a new printer, simplify the experience by showing a drop-down with the supported printer drivers.

Specifically, the printer Id box should have a drop down.

Example contents of the drop-down:
```
bg.dt.isl.com://COM<Number>
bg.dt.tcp://<tcp-address>
bg.tr.bt://COM<Number>
```

After the user selects an entry, it is loaded in the text box for further specification.

There is no need for complicated helpers. Just a bunch of texts.

**Comment by g-vvv** [comment]
v.1.0.1017.1400
