### ISSUE TITLE
Improve the console

### ISSUE THREAD

**Issue by i-argentinski** [erpnet/ErpNet.FP#12]
Make the following changes to the console window:

(1) Use fixed-width font

(2) The default console window size should be able to show 80x25 characters.

(3) [BUG] The messages are shown on the same line - not CR & LF-ed to new line for each message.

(4) [OPTIONAL] Support setting "Console Verbosity Level" in the tray menu.
Possible levels:
* Minimal - Only Show Warnings/Errors
* Normal - Show Normal Messages (DEFAULT)
* Debug - Maximum Verbosity

The "Normal" level (or whatever it is called) should include "Found 3 printers" and similar messages. The idea is that, by default, we can see the detected/configured printers in the default console.

NOTE: Changing the verbosity level should be saved to the config and applied to the running instance immediately.

**Comment by dekiland** [comment]
- 80 x 25 is too small, we will use 120 x 30, like cmd.exe windows default.
- Normal default mode will be used, when user wants less or more info, can alter appsettings.json Logging Level.

**Comment by i-argentinski** [comment]
(3) CR & LF is not well implemented. If I resize the console, the text inside it still wraps on the first line.

New sub-task:
(5) The console window should have vertical scroll bar.
