### ISSUE TITLE
Allow empty quantity

### ISSUE THREAD

**Issue by iveivanov** [erpnet/ErpNet.FP#120]
It is a good idea to allow a request without quantity in Json body.
The goal is to print receipt in this form:

![image](https://user-images.githubusercontent.com/50704486/68477194-76549b80-0235-11ea-9710-493699e44c97.png)

We put the quantity in comment text and only text and amount in a fiscal row.

**Comment by g-vvv** [comment]
![IMG_20191108_173712](https://user-images.githubusercontent.com/37645906/68488782-7745f700-024e-11ea-8542-daa1286db046.jpg)

**Comment by g-vvv** [comment]
It not always works, when there is no quantity present. For example, for Datecs works, for Tremol, do not work, it always prints the quantity (default = 1). I will try with Daisy, Eltrade, and others.

**Comment by g-vvv** [comment]
![15732276750482753703973189045021](https://user-images.githubusercontent.com/37645906/68489050-ff2c0100-024e-11ea-80d3-21c2f220b85a.jpg)

**Comment by g-vvv** [comment]
Daisy, Eltrade, works!

**Comment by g-vvv** [comment]
This is the sample receipt I use for these tests:
```
{  
   "uniqueSaleNumber":"DT122222-0001-0000900",
   "items":[  
      {  
         "text":"Toy",
         "unitPrice":15.00,
         "taxGroup":2
      },
      {  
         "text":"Ball",
         "unitPrice":20.00,
         "taxGroup":2
      }
   ],
   "payments":[  
      {  
         "amount":35.00,
         "paymentType":"cash"
      },
   ]
}
```

**Comment by g-vvv** [comment]
Binaries for the new release: 1.0.1108.1800
