### ISSUE TITLE
Print Reversal Receipt with reason "tax-base-reduction" return error

### ISSUE THREAD

**Issue by svetoslavopinchev** [erpnet/ErpNet.FP#123]
Tested with Daisy compact M
The receipt bellow return error
{
    "uniqueSaleNumber": "DY449885-0001-0000159",
    "receiptNumber": "000069",
    "receiptDateTime": "2019-11-17T12:30:45",
    "fiscalMemorySerialNumber": "36607921",
    "reason": "tax-base-reduction",
    "items": [
        {
            "text": "DEK-10",
            "quantity": 2,
            "unitPrice": 0.39,
            "taxGroup": 2
        },
        {
            "text": "KEYS",
            "type": "comment"
        }
    ],
    "payments": [
        {
            "amount": 0.78,
            "paymentType": "cash"
        }
    ]
}

returned error
{
    "errors": {
        "reason": [
            "Error converting value \"tax-base-reduction\" to type 'ErpNet.FP.Core.ReversalReason'. Path 'reason', line 6, position 34."
        ],
        "reversalReceipt": [
            "The reversalReceipt field is required."
        ]
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|cd95ac2c-47268599b3ffd96e."
}

The same  Reversal Receipt work correctly with reason "taxbase-reduction"  instead "tax-base-reduction"

**Comment by g-vvv** [comment]
You spell it wrong: it is "taxbase-reduction", not "tax-base-reduction".
