### ISSUE TITLE
Add button "Sync time" in printer definition in the Admin console

### ISSUE THREAD

**Issue by iveivanov** [erpnet/ErpNet.FP#124]
It is a good idea to have an option in Admin console to sync printer time with time at admin console's pc.

I think that button in printer definition will be a solution.

![image](https://user-images.githubusercontent.com/50704486/69253456-57eb8a00-0bbd-11ea-8f56-8f16631ed42d.png)

**Comment by i-argentinski** [comment]
Both words should start with cap letter - Sync Time.

If possible, add hint, for example - "Sync the printer time with the current time on the PC".

**Comment by g-vvv** [comment]
New version released.

![image](https://user-images.githubusercontent.com/37645906/69443643-87ce9500-0d57-11ea-8279-1e418120ce67.png)
