### ISSUE TITLE
Add to printer config  itemTextLength and commentTextLength

### ISSUE THREAD

**Issue by iveivanov** [erpnet/ErpNet.FP#130]
It is a good idea to have possibility to define itemTextLength and commentTextLength in printer definition, because printer documentation is not correct and ErpNet.FP doesn't return proper values for some devices.
This can be a config file then can be updated remotely or locally.

**Comment by iveivanov** [comment]
Hello,

Thank you for the new settings! 
But there is a problem with them. After I set the commentTextLength and apply, the server returned original values:
![image](https://user-images.githubusercontent.com/50704486/70818844-65bbb600-1ddd-11ea-94b8-0aa10b115722.png)

![image](https://user-images.githubusercontent.com/50704486/70818873-766c2c00-1ddd-11ea-877d-f450e2a4c767.png)

**Comment by g-vvv** [comment]
There is new version, v.1.0.1213.1913. Try with it.
