### ISSUE TITLE
Strange responce 

### ISSUE THREAD

**Issue by StoyanMalchev** [erpnet/ErpNet.FP#139]
[2020-01-21 13:09 ...]
POST: http://localhost:8001/printers/dt779201/receipt

The ribbon ends...

HTTP Response -- Code: 200, Body(35):
{"taskId":"GJMPGqQhAkmVu2En6kPaEA"}

What does this mean?

Operation failure is registered, but receipt is included in XReport and NAP. 

[debug_Vilda.log](https://github.com/erpnet/ErpNet.FP/files/4092914/debug_Vilda.log)

**Comment by g-vvv** [comment]
Please use idempotent requests in production. Read more about it at Protocol.md.
