### ISSUE TITLE
Problem with duplicate

### ISSUE THREAD

**Issue by StoyanMalchev** [erpnet/ErpNet.FP#144]
Response is 
"ok":true,
but nothing printed.
[debug.log](https://github.com/erpnet/ErpNet.FP/files/4127358/debug.log)

**Comment by rosen4o** [comment]
On some fiscal devices duplicate should be enabled in the settings and then you are able to print it.

**Comment by g-vvv** [comment]
@rosen4o is absolutely right. We will extend the documentation with information how to enable the printing of the duplicate for most of the fiscal devices. Because in general, it is disabled by default, unless expliciltly permitted by the user or the servicing company.
