### ISSUE TITLE
Create a new Debug Log for each day.

### ISSUE THREAD

**Issue by iveivanov** [erpnet/ErpNet.FP#152]
Currently, we have a new Debug log after a restart of ErpNet.FP.  But restarts may happen quite rare so the Debug log files become very big and they become difficult for reading and investigation.

![image](https://user-images.githubusercontent.com/50704486/85836946-17ca3680-b7a0-11ea-955c-9aad09ea05c8.png)

The idea is to have smaller and readable Debug logs

**Comment by iveivanov** [comment]
The request is to create a new Debug log file every day.

**Comment by dilyanrusev** [comment]
fixed with v1.0.3000.0000
