### ISSUE TITLE
Issues with Eltrade

### ISSUE THREAD

**Issue by skito** [erpnet/ErpNet.FP#167]
Just to continue the thread from #166 , as I didn't had a chance to respond. 

@g-vvv As stated in the original issue itself the NRA terminal is working well on both Eltrade A1 devices and the Eltrade service center is confirming that. Also both devices are in production - they print real receipts for customers. I've went thought all the docs and code before open the issue.

My question is simple. Do you think there might be any other config/hardware relation to the error, beside the NRA terminal?

Beside that great job with library guys! It rocks!

**Comment by g-vvv** [comment]
You will not find any other answers than previously given. So please check your device status again. Also, you could try with older versions of ErpNet.FP if you think that latest version of service broke something that worked before.
