### ISSUE TITLE
End Pinpad Day on DatecsPay pinpad connected to Datecs X device

### ISSUE THREAD

**Issue by krcenov** [erpnet/ErpNet.FP#172]
Hello,
Is it possible to implemet pinpad end day in your application because otherwise 
ErpNet.FP is not usable with pinpad when you are unable to end pinpad day?

**Comment by krcenov** [comment]
Usually a little group of people still do Z reports manually.
And no, its not the same for printers, because when u send a Z report command to the printer the printer does not ask if you want to end the day on the pinpad aswell.
It would be very usefull if you implement this function because it will make the pinpad implementation in ErpNet.FP complete.

**Comment by o-ivanov** [comment]
Z and X reports for pinpad added for Datex-X devices with activated pinpad.
