### ISSUE TITLE
What about support of dateacs dp150 MX

### ISSUE THREAD

**Issue by bobfh** [erpnet/ErpNet.FP#183]
What about support of datecs dp150 MX?

**Comment by iveivanov** [comment]
Hello,

Try with bg.dt.x.isl protocol.

**Comment by bobfh** [comment]
> 

 2023-08-09 17:51:00 INF] Starting the service, version 1.1.0.721...
[ 2023-08-09 17:51:00 INF] Autodetecting local printers...
[ 2023-08-09 17:51:00 INF] Probing (1/9)bg.dt.x.isl.com://COM8...
[ 2023-08-09 17:51:01 INF] COM8 <<< 01-30-30-32-3B-21-30-30-35-3A-31-05-30-31-3F-33-03
[ 2023-08-09 17:51:01 INF] Keep Alive Background Service is started.
[ 2023-08-09 17:51:01 INF] Opening the com port COM8
[ 2023-08-09 17:51:01 INF] COM8 >>> 16-01-30-30-36-3A-21-30-30-35-3A-44-50-2D-31-35-30-4D-58-2C-36-30-39-34-32-38-20-32-30-4A-75-6C-32-33-20-31-33-35-33-2C-39-34-36-30-2C-30-30-30-30-30-30-30-30-2C-20-20-20-20-30-32-35-30-30-30-30-32-04-80-80-80-80-84-82-80-80-05-31-31-31-32-03
[ 2023-08-09 17:51:01 INF] Device at COM8 incompatible with protocol bg.dt.x.isl: invalid device info returned.
[ 2023-08-09 17:51:01 INF] Probing (2/9)bg.dt.c.isl.com://COM8...
[ 2023-08-09 17:51:01 INF] COM8 <<< 01-25-21-5A-31-05-30-30-3D-36-03
[ 2023-08-09 17:51:01 INF] Com port COM8 allready opened!
[ 2023-08-09 17:51:01 INF] COM8 >>> 16
[ 2023-08-09 17:51:01 INF] COM8 >>> 15
[ 2023-08-09 17:51:01 INF] COM8 <<< 01-25-21-5A-31-05-30-30-3D-36-03
[ 2023-08-09 17:51:01 INF] Com port COM8 allready opened!
[ 2023-08-09 17:51:01 INF] COM8 >>> 16
[ 2023-08-09 17:51:01 INF] COM8 >>> 15
[ 2023-08-09 17:51:01 INF] COM8 <<< 01-25-21-5A-31-05-30-30-3D-36-03
[ 2023-08-09 17:51:01 INF] Com port COM8 allready opened!
[ 2023-08-09 17:51:01 INF] COM8 >>> 16
[ 2023-08-09 17:51:01 INF] COM8 >>> 15
[ 2023-08-09 17:51:01 INF] COM8 <<< 01-25-21-5A-31-05-30-30-3D-36-03
[ 2023-08-09 17:51:01 INF] Com port COM8 allready opened!
[ 2023-08-09 17:51:01 INF] COM8 >>> 16
[ 2023-08-09 17:51:01 INF] COM8 >>> 15
[ 2023-08-09 17:51:01 INF] COM8 <<< 01-25-21-5A-31-05-30-30-3D-36-03
[ 2023-08-09 17:51:01 INF] Com port COM8 allready opened!
[ 2023-08-09 17:51:01 INF] COM8 >>> 16
[ 2023-08-09 17:51:01 INF] COM8 >>> 15
[ 2023-08-09 17:51:01 INF] COM8 <<< 01-25-21-5A-31-05-30-30-3D-36-03
[ 2023-08-09 17:51:01 INF] Com port COM8 allready opened!
[ 2023-08-09 17:51:01 INF] COM8 >>> 16
[ 2023-08-09 17:51:01 INF] COM8 >>> 15
[ 2023-08-09 17:51:01 INF] Device at COM8 incompatible with protocol bg.dt.c.isl: invalid device info returned.
[ 2023-08-09 17:51:01 INF] Probing (3/9)bg.dt.p.isl.com://COM8...
[ 2023-08-09 17:51:01 INF] Device at COM8 incompatible with protocol bg.dt.p.isl: invalid device info returned.
[ 2023-08-09 17:51:01 INF] Probing (4/9)bg.ed.isl.com://COM8...
[ 2023-08-09 17:51:01 INF] Device at COM8 incompatible with protocol bg.ed.isl: invalid device info returned.
[ 2023-08-09 17:51:01 INF] Probing (5/9)bg.dy.isl.com://COM8...
[ 2023-08-09 17:51:01 INF] Device at COM8 incompatible with protocol bg.dy.isl: invalid device info returned.
[ 2023-08-09 17:51:01 INF] Probing (6/9)bg.in.isl.com://COM8...
[ 2023-08-09 17:51:01 INF] Device at COM8 incompatible with protocol bg.in.isl: invalid device info returned.
[ 2023-08-09 17:51:01 INF] Probing (7/9)bg.is.icp.com://COM8...
[ 2023-08-09 17:51:01 INF] COM8 <<< 02-30-30-30-30-30-30-30-3C-38-3E-03
[ 2023-08-09 17:51:01 INF] Com port COM8 allready opened!
[ 2023-08-09 17:51:02 ERR] Timeout occured while reading from com port 'COM8'
[ 2023-08-09 17:51:02 INF] COM8 Cannot read from channel: Timeout occured while reading from com port 'COM8'
[ 2023-08-09 17:51:02 INF] Device at COM8 incompatible with protocol bg.is.icp: invalid device info returned.
[ 2023-08-09 17:51:02 INF] Probing (8/9)bg.zk.zfp.com://COM8...
[ 2023-08-09 17:51:02 INF] COM8 <<< Ping: 9
[ 2023-08-09 17:51:02 INF] Opening the com port COM8
[ 2023-08-09 17:51:03 ERR] Timeout occured while reading from com port 'COM8'
[ 2023-08-09 17:51:03 INF] Timeout, try again!
[ 2023-08-09 17:51:03 INF] COM8 <<< Ping: 9
[ 2023-08-09 17:51:03 INF] Opening the com port COM8
[ 2023-08-09 17:51:04 ERR] Timeout occured while reading from com port 'COM8'
[ 2023-08-09 17:51:04 INF] Timeout, try again!
[ 2023-08-09 17:51:04 INF] COM8 <<< Ping: 9
[ 2023-08-09 17:51:04 INF] Opening the com port COM8
[ 2023-08-09 17:51:05 ERR] Timeout occured while reading from com port 'COM8'
[ 2023-08-09 17:51:05 INF] Timeout, try again!
[ 2023-08-09 17:51:05 INF] COM8 Error while waiting device to be ready: ping timeout
[ 2023-08-09 17:51:05 INF] COM8 <<< Ping: 9
[ 2023-08-09 17:51:05 INF] Opening the com port COM8
[ 2023-08-09 17:51:06 ERR] Timeout occured while reading from com port 'COM8'
[ 2023-08-09 17:51:06 INF] Timeout, try again!
[ 2023-08-09 17:51:06 INF] COM8 <<< Ping: 9
[ 2023-08-09 17:51:06 INF] Opening the com port COM8
[ 2023-08-09 17:51:07 ERR] Timeout occured while reading from com port 'COM8'
[ 2023-08-09 17:51:07 INF] Timeout, try again!
[ 2023-08-09 17:51:07 INF] COM8 <<< Ping: 9
[ 2023-08-09 17:51:07 INF] Opening the com port COM8
[ 2023-08-09 17:51:07 ERR] Timeout occured while reading from com port 'COM8'
[ 2023-08-09 17:51:07 INF] Timeout, try again!
[ 2023-08-09 17:51:07 INF] COM8 Error while waiting device to be ready: ping timeout
[ 2023-08-09 17:51:07 INF] Device at COM8 incompatible with protocol bg.zk.zfp: invalid device info returned.
[ 2023-08-09 17:51:07 INF] Probing (9/9)bg.zk.v2.zfp.com://COM8...
[ 2023-08-09 17:51:07 INF] Device at COM8 incompatible with protocol bg.zk.v2.zfp: invalid device info returned.
[ 2023-08-09 17:51:08 INF] Detecting done. Found 0 available printer(s).
[ 2023-08-09 17:51:10 INF] Idle timer elapsed for the com port COM8
[ 2023-08-09 17:51:11 INF] Closing the com port COM8

**Comment by bobfh** [comment]
Pass to operator is 1

**Comment by iveivanov** [comment]
Is this Bulgarian device and protocol?

By default password for operator 1 is "0000"

bg.dt.x.isl - "operator" : "1", "operatorPassword": "0000"

https://github.com/erpnet/ErpNet.FP#default-passwords-we-use-in-the-library

**Comment by bobfh** [comment]
> Is this Bulgarian device and protocol?
> 
> By default password for operator 1 is "0000"
> 
> bg.dt.x.isl - "operator" : "1", "operatorPassword": "0000"
> 
> https://github.com/erpnet/ErpNet.FP#default-passwords-we-use-in-the-library

Its moldavian device from tina.md

**Comment by o-ivanov** [comment]
Hello,
Answer of ID request for your fiscal device is decoded as:
   DP-150MX,609428 20Jul23 1353,9460,00000000,    02500002
and there is missing part from required answer format, which is like:
   FP-700X,2.00 13May20 1042,6331,00000000,**DT52XXXX,**025XXXXX

   Missing part (like "DT52XXXX,") is Fiscal Device Number and is essential and required.
   This means that your device can not be supported by this software.
