### ISSUE TITLE
Service Fails to Reconnect to Printer After Connection Interruption

### ISSUE THREAD

**Issue by RBI7TEC** [erpnet/ErpNet.FP#188]
The ErpNet.FP service fails to reconnect to the printer after a connection interruption. (Device\Network)
Trying to detect manually using the detect button on the admin page or through the API /service/detect doesn't work.
Only after a full service restart does the detection work again and it gets displayed as available correctly.

If you have mutliple printer running over the ErpNet.FP, the jobs  of the other printers are at risk as soon as a full service restart is executed.

**Detail:**
We are using the latest version: ErpNet.FP ver.1.1.0.1110 but it appeared already on the earlier version.
Also, we where able to reproduce the issue on different servers.

**Describe the device(s) you are using:**
Model: Datecs DT-25 MX (bg.dt.x.isl.tcp:X.X.X.X:4999)

**How To Reproduce:**

1. Have a device configured and displayed as available.
2. Block the connection/device with the firewall.
3. Refresh the ERPNet.FP until the printer is not available anymore.
4. Unblock the device and the device doesn't get detected anymore until the service is restarted.

**Expected behavior:**
The autodetect feature should detect the device as soon as it's available again.
Right now it seems like a bug that this is hanging somewhere.

**LOG:**
[2024-08-04 23:25:15 INF] Keep Alive Background Service done.
[XXX:00000005 2024-08-04 23:26:07 INF] -- HTTP Request -- GET: http://localhost:8001/service/detect, Body(0):
[XXX:00000005 2024-08-04 23:26:16 INF] Autodetecting local printers...
[XXX:00000005 2024-08-04 23:26:16 INF] Detecting configured printers...
[XXX:00000005 2024-08-04 23:26:16 INF] X.X.X.X:4999 <<< 01-30-30-32-3B-21-30-30-35-3A-31-05-30-31-3F-33-03
[XXX:00000005 2024-08-04 23:26:16 ERR] Cannot reconnect to X.X.X.X:4999
[XXX:00000005 2024-08-04 23:26:16 INF] X.X.X.X:4999 <<< 01-30-30-32-3B-21-30-30-35-3A-31-05-30-31-3F-33-03
[XXX:00000005 2024-08-04 23:26:16 ERR] Cannot reconnect to X.X.X.X:4999
[XXX:00000005 2024-08-04 23:26:16 INF] X.X.X.X:4999 <<< 01-30-30-32-3B-21-30-30-35-3A-31-05-30-31-3F-33-03
[XXX:00000005 2024-08-04 23:26:16 ERR] Cannot reconnect to X.X.X.X:4999
[XXX:00000005 2024-08-04 23:26:16 INF] X.X.X.X:4999 <<< 01-30-30-32-3B-21-30-30-35-3A-31-05-30-31-3F-33-03
[XXX:00000005 2024-08-04 23:26:16 ERR] Cannot reconnect to X.X.X.X:4999
[XXX:00000005 2024-08-04 23:26:16 INF] X.X.X.X:4999 <<< 01-30-30-32-3B-21-30-30-35-3A-31-05-30-31-3F-33-03
[XXX:00000005 2024-08-04 23:26:16 ERR] Cannot reconnect to X.X.X.X:4999
[XXX:00000005 2024-08-04 23:26:16 INF] X.X.X.X:4999 <<< 01-30-30-32-3B-21-30-30-35-3A-31-05-30-31-3F-33-03
[XXX:00000005 2024-08-04 23:26:16 ERR] Cannot reconnect to X.X.X.X:4999
[XXX:00000005 2024-08-04 23:26:16 INF] Trying XXX DT-25 MX: bg.dt.x.isl.tcp://X.X.X.X:4999, failed

**Additional context**
Windows Server 2022

**Comment by o-ivanov** [comment]
Issue is fixed in release [v1.1.0.1414](https://github.com/erpnet/ErpNet.FP/releases/tag/v1.1.0.1414)
