### ISSUE TITLE
Payment error on async mode cause infinitely running task

### ISSUE THREAD

**Issue by voltmachine** [erpnet/ErpNet.FP#27]
---
name: Bug report
about: Create a report to help us improve
title: 'Payment error on async mode cause infinitely running task'
labels: bug
assignees: ''

---

**Describe the bug**
When try print error receipt, print stopping before payment row and task stay "running" infinitely. The printing stuck to items row.
When try print non error receipt after, his task receive status finished and finalize stucked printing with cancelation. But the first receipt task continue return "running" infinity. 

The same receipt with payment "check" in synchronous mode is finalized correctly.

**Describe the device(s) you are using**
Datecs DP-150 in non-fiscal mode
{"uri":"bg.dt.c.isl.com://COM7","serialNumber":"DT746009","fiscalMemorySerialNumber":"02746009","company":"Datecs","model":"DP-150","firmwareVersion":"265403 08Nov18 1050","itemTextMaxLength":22,"commentTextMaxLength":42,"operatorPasswordMaxLength":8}

**How To Reproduce**
1. Print receipt with payment "check", to force error E404 not allowed in current mode.
2. Task state stay "running" for 30 minutes and continue. The receipt stuck printed to items rows.
3. Print another receipt with payment "cash"
4. The second receipt task_id return status finished, with error E404. The printer finalize stucked print with cancelation.
5. Task first receipt task continue to return "running"
Steps are visible in attached debug.log

**Expected behavior**
In step 2. task should return state finished with error E404.

**Screenshots**
![20190602_143031](https://user-images.githubusercontent.com/46065232/58760630-421cd680-8543-11e9-8ef6-22ad06d8caa8.jpg)
[debug.log.1.zip](https://github.com/erpnet/ErpNet.FP/files/3244729/debug.log.1.zip)

**Additional context**

**Comment by g-vvv** [comment]
Thank you for your report. Bug fixed.
