### ISSUE TITLE
"discount-amount" error on protocol bg.dt.c.isl.com

### ISSUE THREAD

**Issue by voltmachine** [erpnet/ErpNet.FP#30]
**Describe the bug**
Syntax error while print "discount-amount" on protocol bg.dt.c.isl.com
Seems wrong prefix "$" before the amount. The protocol reference points ";"

Executed command:
`Request(31): 'Артикул	Б1.00*1$-0.03'`

Protocol refence:
`31h (49)  [<L1>][<Lf><L2>]<Tab><TaxCd><[Sign]Price>[*<Qwan>][,Perc|;Abs] `

**Describe the device(s) you are using**
Datecs DP-150

**Screenshots**
```
Request(31): 'Артикул	Б1.00*1$-0.03'
>>>1 39 29 31 C0 F0 F2 E8 EA F3 EB 9 C1 31 2E 30 30 2A 31 24 2D 30 2E 30 33 5 30 39 3E 30 3 
<<<16 
<<<1 2B 29 31 4 A1 A0 88 80 84 82 5 30 33 3D 3D 3 
```

**Comment by g-vvv** [comment]
Thank you for your report. Bug fixed.
