### ISSUE TITLE
On error, result is "ok":true.

### ISSUE THREAD

**Issue by voltmachine** [erpnet/ErpNet.FP#32]
When message of type error exists, the print is canceled corectlly, but result "ok" is set to true.
Is not it expected to be false?

```
{
   "taskStatus":"finished",
   "result":{
      "receiptNumber":"",
      "receiptDateTime":"0001-01-01T00:00:00",
      "receiptAmount":0.0,
      "fiscalMemorySerialNumber":"02746009",
      "ok":true,
      "messages":[
         {
            "type":"error",
            "code":"E406",
            "text":"Payment type Check unsupported"
         },
         {
            "type":"info",
            "code":"",
            "text":"Error occured while printing receipt items"
         }
      ]
   }
}}
```

**Comment by g-vvv** [comment]
Thank you for your report. Please provide debug.log, to investigate your case.

**Comment by voltmachine** [comment]
[debug.log](https://github.com/erpnet/ErpNet.FP/files/3248718/debug.log)

**Comment by g-vvv** [comment]
Thank you, I make another build with simplified Ok property. You can try it, because I do not have the test devices @home. If it is OK, I will close the Bug. If the bug is reproduced, then tomorrow will continue with your case.

**Comment by voltmachine** [comment]
Thank you.
I have tested it, it is still "ok":true:
[debug.log](https://github.com/erpnet/ErpNet.FP/files/3248809/debug.log)

**Comment by g-vvv** [comment]
With the new build, I think the bug is resolved. You can try it. The problem was in initialization of descendants of the class DeviceStatus with copy constructor, without copying the Ok property. Thank you again for your feedback and have a nice evening.

**Comment by voltmachine** [comment]
I confirm, it is fixed.
Thank you.
