### ISSUE TITLE
Get a unique workplace identifier

### ISSUE THREAD

**Issue by voltmachine** [erpnet/ErpNet.FP#36]
Get a unique workplace identifier on the device where the ErpNet.FP server is running.
By government requirements for workplaces, from annex 29 points 5, 8, 18, 18.1, 18.9.

It can also help for control fiscal devices usage - set defaults or restrict, when more than one available for a workplace.

For softwares without locally installed modules, it will eliminate the need to install an extra server to obtain workplace id.

Identifier may be a bios serial, drive serial, ethernet adapter or other unique identifier.
Response may be a hash, to keep a fixed length.

Example Request
GET: `/deviceuid`

Example Response
```
{
	"deviceuid": "2C290D367A8020BF6F75F5AB4B0E8F30"
}
```

**Comment by i-argentinski** [comment]
We didn't find and such requirement in N-18, Annex 29, p.5, 8, 18.1 and 18.9.

The only requirement is to have unique fiscal printer id. This is returned by 
* /printers - list of all printers and their serial numbers
* /printers/xxx - information for specific printer

**Comment by voltmachine** [comment]
As I understand workplaces and fiscal printers devices are different nomeclatures.
One workplace (pay desc which collect cash) can print from different printers. 

![capture_06072019_104127](https://user-images.githubusercontent.com/46065232/59088716-f1292b80-8910-11e9-9f08-e67a552678b6.png)

**Comment by g-vvv** [comment]
Added /vars
