### ISSUE TITLE
Unable to print receipts due to encoding issue

### ISSUE THREAD

**Issue by adragostinov** [erpnet/ErpNet.FP#44]
**Describe the bug**
Wrong encoding in the committed file: [BgIslFiscalPrinter.cs](https://github.com/erpnet/ErpNet.FP/blob/master/ErpNet.FP.Core/Drivers/BgIslFiscalPrinter.cs) - the file is saved with ANSI encoding which replaces the Cyrillic characters from the tax group with unreadable ones. This subsequently leads to the inability to process the POST request, returning a syntax error. 
Please commit the file again with UTF-8 encoding.

**Describe the device(s) you are using**
Daisy Perfect S

**How To Reproduce**
Just check the content of the committed file: 

` switch (taxGroup)
            {
                case TaxGroup.TaxGroup1:
                    return "À";
                case TaxGroup.TaxGroup2:
                    return "Á";
                case TaxGroup.TaxGroup3:
                    return "Â";
                case TaxGroup.TaxGroup4:
                    return "Ã";
                case TaxGroup.TaxGroup5:
                    return "Ä";
                case TaxGroup.TaxGroup6:
                    return "Å";
                case TaxGroup.TaxGroup7:
                    return "Æ";
                case TaxGroup.TaxGroup8:
                    return "Ç";
                default:
                    throw new StandardizedStatusMessageException($"Tax group {taxGroup} unsupported", "E411");
            }`

**Expected behavior**
Unable to print receipts.

**Comment by g-vvv** [comment]
Thanks, it is fixed.
