### ISSUE TITLE
Retain COM port open

### ISSUE THREAD

**Issue by palex** [erpnet/ErpNet.FP#47]
**ErpNet Retains COM port open although there is no printer**
After autodection phase ErpNet continue without close serial port that no printer detected.

**POS terminals, scales or other hardware on this ports will not to work**
If we have POS terminals, scales or other hardware that communicating occasionally they will fail on next try, because port is already opened.

I am not a C# master but suggest fixing in Transport.cs -> ComTransport.cs
```csharp
        public override void CloseChannel(string address)
        {
            if (openedChannels.TryGetValue(address, out Channel? channel))
            {
                channel.Dispose();
                openedChannels.Remove(address);
            }
        }
```
and in Provider.cs after drivers iteration try:
```csharp
                    if (!Found)
                    {
                        transport.CloseChannel(availableAddress.address); 
                    }
```
That fix is working for me.

**Comment by palex** [comment]
gute Arbeit

**Comment by g-vvv** [comment]
Vielen Dank, mein alter Freund :)

На вт, 2 юли 2019 г., 20:44 palex <notifications@github.com> написа:
