### ISSUE TITLE
DP-150

### ISSUE THREAD

**Issue by dsetekh** [erpnet/ErpNet.FP#50]
Hi,
I'm trying to test with Datecs DP-150 but it can not be detected. 
FPInit detects it and test fiscal receipts can be printed, so it is correctly attached/setup.
Can you please help out.
Thanks

**Comment by iveivanov** [comment]
I think there is a problem with Autodetect in the last version.
I have FP attached to port 5 and 11, but Autodetect search only on port 9.

-- HTTP Request -- GET: http:/localhost:8001/service/detect, Body(0):
Autodetecting local printers...
Probing bg.dt.x.isl.com://COM9...
Request(5A): '1'
>>>1 30 30 32 3B 21 30 30 35 3A 31 5 30 31 3F 33 3
Timeout occured while writing to com port 'COM9'
Probing bg.dt.c.isl.com://COM9...
Request(5A): '1'
>>>1 25 21 5A 31 5 30 30 3D 36 3
Timeout occured while writing to com port 'COM9'
Probing bg.dt.p.isl.com://COM9...
Request(5A): '1'
>>>1 25 21 5A 31 5 30 30 3D 36 3
Timeout occured while writing to com port 'COM9'
Probing bg.ed.isl.com://COM9...
Request(5A): '1'
>>>1 25 21 5A 31 5 30 30 3D 36 3
Timeout occured while writing to com port 'COM9'
Probing bg.dy.isl.com://COM9...
Request(5A): '1'
>>>1 25 21 5A 31 5 30 30 3D 36 3
Timeout occured while writing to com port 'COM9'
Probing bg.in.isl.com://COM9...
Request(5A): '1'
>>>1 25 21 5A 31 5 30 30 3D 36 3
Timeout occured while writing to com port 'COM9'
Probing bg.zk.zfp.com://COM9...
Request(60): ''
>>> Ping >>> 9 <<< Timeout occured while writing to com port 'COM9'
Request(21): ''
>>> Ping >>> 9 <<< Timeout occured while writing to com port 'COM9'
Probing bg.zk.v2.zfp.com://COM9...
Request(60): ''
>>> Ping >>> 9 <<< Timeout occured while writing to com port 'COM9'
Request(21): ''
>>> Ping >>> 9 <<< Timeout occured while writing to com port 'COM9'
Detecting configured printers...
Detecting done. Found 0 available printer(s).
-- HTTP Response -- Code: 200, Body(0):
-- HTTP Request -- GET: http:/localhost:8001/printers, Body(0):
-- HTTP Response -- Code: 200, Body(2):
{}
-- HTTP Request -- GET: http:/localhost:8001/service/printers, Body(0):
-- HTTP Response -- Code: 200, Body(2):
{}
