### ISSUE TITLE
Endless cycle when received unrecognized data from COM

### ISSUE THREAD

**Issue by palex** [erpnet/ErpNet.FP#51]
**Autodetect hang when COM has unsupported device**
I have connected only standard serial cable without device, but autodetect fail when probing for Tremol printer.

**How To Reproduce**
Connect only standard serial cable (in my case for Datecs label printer).

**Expected behavior**
After a few unrecognized tries give up and continue.
[debug.log.3.zip](https://github.com/erpnet/ErpNet.FP/files/3365310/debug.log.3.zip)

**Comment by g-vvv** [comment]
So, when the empty cable returns a wrong code, the Tremol driver by the protocol, tries to wait a valid signal in an infinite loop. I'll fix this.
