### ISSUE TITLE
Cash on delivery payment for datecs CIs

### ISSUE THREAD

**Issue by voltmachine** [erpnet/ErpNet.FP#52]
For webshops to print cash on delivery usually is used method "credit".
Will be good to add this payment as Reserved2, which is currently not used in Cls protocol

_‘N’ - Плащане с кредит;_ 
```
                case PaymentType.Reserved2:
                    return "N";
```

```
               case PaymentType.Cash:
                    return "P";
                case PaymentType.Card:
                    return "C";
                case PaymentType.Reserved1:
                    return "D";
                default:
                    throw new StandardizedStatusMessageException($"Payment type {paymentType} unsupported", "E406");
```

Also currently unsupported payment "check", can be attached to voucher
_‘I’ - Плащане с ваучер;_

**Comment by g-vvv** [comment]
Duplicated. For more information see issue #40
