### ISSUE TITLE
The command is not allowed in the current fiscal mode?

### ISSUE THREAD

**Issue by StoyanMalchev** [erpnet/ErpNet.FP#54]
DP-150
Режим 1: РЕГИСТРИРАНЕ
Problem on printing receipt:
[debug.log](https://github.com/erpnet/ErpNet.FP/files/3373285/debug.log)

**Comment by iveivanov** [comment]
Hello, 
Try to print Z report first.

**Comment by StoyanMalchev** [comment]
Same problem after Z REPORT:
[debug.log](https://github.com/erpnet/ErpNet.FP/files/3373455/debug.log)

**Comment by g-vvv** [comment]
Please read the info message: "A service receipt with 90-degree rotated text printing is open".
So now, you can solve your problem with closing the previously opened 90-degree non-fiscal rotated text receipt.

**Comment by StoyanMalchev** [comment]
About  message   ...90-degree rotated text
I accept reply from DATECS:
> в модел DP150, както и във всички устройства от тяхната група, нямаме печат на бон, завъртян на 90 градуса.

**Comment by iveivanov** [comment]
What happens if you try to print fiscal receipt thru the keyboard of fiscal device?

**Comment by StoyanMalchev** [comment]
No problems when print thru keyboard.

**Comment by g-vvv** [comment]
Please close previously opened non-fiscal receipt, no mater if it is
rotated or not.

На ср, 10 юли 2019 г., 9:27 StoyanMalchev <notifications@github.com> написа:
