### ISSUE TITLE
Android version of the ErpNet.FP service

### ISSUE THREAD

**Issue by g-vvv** [erpnet/ErpNet.FP#55]
To build the android service we have some drawbacks. Because we can not use kestrel in the android version of ErpNet.FP (.net core 3 and asp.net core - **kestrel is not supported** for android, for now), **we will use another, lightweight web server.** 
To ensure the service continuity, like in cases like rotation or switching between applications, we will implement **ErpNet.FP as a frontend service** (frontend services **use more battery**, but will be **always available**, which **is our goal** here). 
Of course **we are open to any suggestions**, advice, and guidance from people who have gone through this road, and have a better solution.

**Comment by i-argentinski** [comment]
Currently, this project is discontinued.
