### ISSUE TITLE
Problem with zip archives in assets under Releases tab

### ISSUE THREAD

**Issue by wqweto** [erpnet/ErpNet.FP#60]
**Describe the bug**
JFYI, the released zip archives are using LZMA (compression method 14) which prevents them from being uncompressed with anything but 7-zip utility.

**How To Reproduce**
Download `win-x86.zip` from assets in Releases tab and right-click it in File Explorer. Choose `Извличане на всички...` option and try to extract to a sub-folder.

**Expected behavior**
Zip archives in assets being compressed with most compatible Deflate method.

**Screenshots**
![image](https://user-images.githubusercontent.com/987963/61548530-94b04480-aa56-11e9-8935-8093540ded4b.png)

**Additional context**
This might be done on purpose to filter out non-developers which are not aware of 7-zip utility as the assets are part of early pre-releases. . . Clever!

**Comment by g-vvv** [comment]
In the next release, we will use only common compression algorithms, available by default in all supported platforms.
