### ISSUE TITLE
In Admin Page button "Delete printer" not working

### ISSUE THREAD

**Issue by iveivanov** [erpnet/ErpNet.FP#62]
**Describe the bug**
When I'm trying to delete printer with "Delete printer" button in Configured Printers section, the printer appears again after a refresh. 

**Describe the device(s) you are using**
I'm making test with FP-700X

**How To Reproduce**
1. The printer is connected to PC and working correctly.
2. Disconnect printer from PC
3. Click "Detect printers" in Admin Page
4. The printer is still there and it is appeared as Ready
5. Click button "Delete printer"
6. The page automatically detects printer again
7. The printer is still there and it is appeared as Ready

**Expected behavior**
I expect deleted printer to not showing as a printer in the Admin page

**Comment by g-vvv** [comment]
Fixed, but please wait for new binary releases.
