### ISSUE TITLE
Incorect error Mesage "isComment\" is deprecated in Item 2. Use \"type\" : \"comment\" instead

### ISSUE THREAD

**Issue by iveivanov** [erpnet/ErpNet.FP#65]
I have Json without "isComment", but still I'm receiving a message ""isComment\" is deprecated in Item 2. Use \"type\" : \"comment\" instead"

Here is the Request:

{
	"uniqueSaleNumber": "DY423793-0001-0000002",
	"items" : 
	[
		{
			"text": "Cheese",
			"quantity": 1,
			"unitPrice": 12,
			"taxGroup": 2
		},
		{
			"text": "Additional comment to the cheese...",
			"type": "comment"
		},
		{
			"text": "Milk",
			"quantity": 2,
			"unitPrice": 10,
			"taxGroup": 2,
			"priceModifierValue": 10,
			"priceModifierType": "discount-percent"
		}
	],
	"Payments" : [
		{
			"paymentType": "cash",
			"amount": "20"
		},
		{
			"paymentType": "check",
			"amount": "10"
		}
	]
}

I receive this response

{
    "ok": false,
    "messages": [
        {
            "type": "warning",
            "code": "W401",
            "text": "Item 2: \"isComment\" is deprecated in Item 2. Use \"type\" : \"comment\" instead"
        },
        {
            "type": "error",
            "code": "E406",
            "text": "Payment type Check unsupported"
        },
        {
            "type": "info",
            "text": "Error occured at Payment 2"
        }
    ]
}

Here is an error with "Payment type" but this is another problem. I there is no second error I don't receive the first error.

I test with FP-700X wich support "check" payment type.
![image](https://user-images.githubusercontent.com/50704486/61789839-61870000-ae1e-11e9-88fc-e93fd8559ebf.png)

**Comment by g-vvv** [comment]
Fixed, but please wait for new binary releases.
