### ISSUE TITLE
Tremol fiscalMemorySerialNumber

### ISSUE THREAD

**Issue by dsetekh** [erpnet/ErpNet.FP#71]
Device: Tremol FP03

Reproduce Request ( any OK status fiscal receipt request ):

> {
>   "uniqueSaleNumber": "ZK111111-0001-0000700",
>   "items": [
>     {
>       "text": "TEST_1",
>       "quantity": 1,
>       "unitPrice": 19.99,
>       "taxGroup": 2
>     }
>    ],
>   "payments": [
>       {
>       "amount": 19.99,
>       "paymentType": "cash"
>     }
>   ]
> }

Current Response:

> {
>     "receiptNumber": "000085",
>     "receiptDateTime": "2019-07-30T16:45:10",
>     "receiptAmount": 0,
>     "fiscalMemorySerialNumber": "",
>     "ok": true,
>     "messages": []
> }

Expected Response:

> {
>     "receiptNumber": "000085",
>     "receiptDateTime": "2019-07-30T16:45:10",
>     "receiptAmount": 0,
>     "fiscalMemorySerialNumber": "1234567",
>     "ok": true,
>     "messages": []
> }

! On error response the fiscalMemorySerialNumber is correctlly populated !

**Comment by i-argentinski** [comment]
The fiscal printer should be fiscalized. Otherwise, some of the functions are not working with Tremol.

**Comment by dsetekh** [comment]
Sorry didn't know that. My bad
