### ISSUE TITLE
Confirmation box when SETUP has completed

### ISSUE THREAD

**Issue by i-argentinski** [erpnet/ErpNet.FP#73]
When SETUP for Windows has completed, show a confirmation box with the following message:

Installation of the Windows service "ErpNet.FP" has completed. 

Include buttons:
"Show Admin" (if possible; should open the default admin web page)
"OK" (both letters are caps)

**Comment by g-vvv** [comment]
New installer is built and the binary ErpNet.FP.Setup.msi is updated.
