### ISSUE TITLE
Small changes to the admin page

### ISSUE THREAD

**Issue by i-argentinski** [erpnet/ErpNet.FP#74]
(1)  The links at the bottom of the admin page are outdated and have to be changed.
(For example, "Download" still points to sourceforge)

TASK: Replace " Source • Docs and examples • Download " with ONLY one link:
"Visit ErpNet.FP on GitHub" - the link should be:
https://github.com/erpnet/ErpNet.FP

Anything more than this is just confusing for the users.

(2) Take down the sourceforge download site
Users are still downloading from there, making them use very old versions.
Just stop this site.

(3) Is the postman site still working?
If so, take it down.

**Comment by g-vvv** [comment]
- Postman collection and account deleted.
- Sourceforge binaries deleted, and account is disabled.
