### ISSUE TITLE
(Proposal) Watchdog for the service / file install version

### ISSUE THREAD

**Issue by dsetekh** [erpnet/ErpNet.FP#81]
Proposal for Enhancement :
Watchdog ( can be implemented as another service or application ) that monitors the service and tries to auto-recover it on need.
Additional:
Same Watchdog may 'cover' the file install / application version and try to recover from accidental exits / task kills.
As a minimum check if 'task is running' for the 'file install version', so less then elegant scheduled 'tasklist'/'get-process' solutions are not needed where such behavior is not implemented it in the service requester / main application in code.

**Comment by g-vvv** [comment]
There are multiple watchdog solutions for services or applications, available for Linux, macOS, Windows. This is not the purpose of this library. We're out of the library's focus. So I will close this issue.
