### ISSUE TITLE
Windows Installer - Adding Icon on Desktop for the Admin Page

### ISSUE THREAD

**Issue by g-vvv** [erpnet/ErpNet.FP#84]
Windows Installer - Will add Icon on Desktop for accessing the Admin Page - http://localhost:8001 in the default configuration.

**Comment by i-argentinski** [comment]
If possible, create also a shortcut (without folder) in the start menu.

For "All users".

**Comment by g-vvv** [comment]
![image](https://user-images.githubusercontent.com/37645906/62723863-5c2ed580-ba1a-11e9-885e-302aee46b93a.png)

**Comment by g-vvv** [comment]
![image](https://user-images.githubusercontent.com/37645906/62724003-ab750600-ba1a-11e9-8870-0baa27b1be0e.png)
