### ISSUE TITLE
Changes in Issue#72 not implemented in Service MSI ( last version - mismatched/typo version )

### ISSUE THREAD

**Issue by dsetekh** [erpnet/ErpNet.FP#85]
The changes from Issue#72 ( Extended Receipt ) seems are not implemented in the MSI version (v.1.0.801.1801 / typo in WEB as ver.1.0.731.1731):

Reproduce:
{
  "uniqueSaleNumber": "DT279013-DD01-0000001",
  "items": [
    {
      "text": "Cheese",
      "quantity": 1,
      "unitPrice": 12,
      "taxGroup": 2
    },
    {
      "type": "comment",
      "text": "Additional comment to the cheese..."
    },
    {
      "text": "Milk",
      "quantity": 2,
      "unitPrice": 10,
      "taxGroup": 2,
      "priceModifierValue": 10,
      "priceModifierType": "discount-percent"
    }
  ],
  "payments": [
    {
      "amount": 50,
      "paymentType": "cash"
    },
    {
      "amount": -20,
      "paymentType": "change"
    }
  ]
}

Response :
    "errors": {
        "payments[1].paymentType": [
            "Error converting value \"change\" to type 'ErpNet.FP.Core.PaymentType'. Path 'payments[1].paymentType', line 30, position 29."
        ]
    },
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|74374cb-439db98647fe149a."
}

**Comment by g-vvv** [comment]
Yes, changes are in source code. But please wait for the next release of
binaries.

На пт, 9 авг 2019 г., 13:35 dsetekh <notifications@github.com> написа:
