### ISSUE TITLE
reversal receipt answer

### ISSUE THREAD

**Issue by persuader** [erpnet/ErpNet.FP#87]
I am printing reversal receipts on datecs model - fp800.

When there is no error the answer is like the printer status answer. 

I think it will be better to implement the receipt type of answer when i get.

  "receiptNumber": 
  "receiptDateTime" : ,
  "receiptAmount": ,
  "fiscalMemorySerialNumber": "

I see that the datecs protocol - 2Eh (46)

Returns the Allreceipt and FiscReceipt counters so i think this is possible. 

Can this be implemented?

**Comment by g-vvv** [comment]
By design, "reversalreceipt" does not return the same answer as "receipt".
You want us to implement the same return parameters for "reversalreceipt", as "receipt"?
Please confirm.
