### ISSUE TITLE
Secure access to server

### ISSUE THREAD

**Issue by moynzzz** [erpnet/ErpNet.FP#93]
**Is your feature request related to a problem? Please describe.**
There must be some way to secure a publicly available server. Currently I am using a server which can be opened from everyone because it is publicly available by typing some IP. Anybody can open that link and trigger a report or send a POST request and trigger a receipt.

**Describe the solution you'd like**
There should be a way to authenticate yourself to the server so any not authorized request should not trigger my fiscal devices to print receipts. Maybe an implementation with json web tokens (JWT) will be good enough.

**Describe alternatives you've considered**
The only alternative I currently think of is that I should restrict access by using systems firewall or something like that which will block access from all but specific IP but I think this is not secure enough and doesn't fit all situations.

**Comment by i-argentinski** [comment]
It is not suggested that you publicly open a port to a fiscal printer, managed by ErpNet.FP. The free print server is not implementing any kind of security.

It is suggested that you implement some front security and use the print server only internally.
