### ISSUE TITLE
text line general

### ISSUE THREAD

**Issue by abasbg** [erpnet/ErpNet.FP#96]
Бихте ли добавили root ниво с текст.
Трябват допълнителни редове за описание извън артикулите. 
Целта е да се изпрати към принтера текст с име на клиент и т,н. останалите реквизити за фактура например.
В момента има text само в items.

**Comment by i-argentinski** [comment]
Add comment lines before or after the line items, depending on wherher you need header or footer.

Such line items will be indistinguishable from root level header or footer.

**Comment by abasbg** [comment]
ok. 10x.

**Comment by g-vvv** [comment]
Resolved with issue #129
