### ISSUE TITLE
Mixed payment error with Datecs

### ISSUE THREAD

**Issue by dsetekh** [erpnet/ErpNet.FP#97]
When Card and Cash payment with Change is issued as request the fiscal unit may fail with General Error and stay unusable with 'open fiscal receipt' status

Units:
DATECS DP-150 ; TREMOL ZP03 ( as verification unit )

Reproduce:
--- GENERAL ERROR on Datecs Request---
Datecs Unit is stuck in 'open fiscal receipt' with General Error thrown
Tremol is working OK with this request
EXAMPLE:
{
  "uniqueSaleNumber": "DT122222-0001-0000900",
  "items": [
    {
      "text": "TEST_1",
      "quantity": 1,
      "unitPrice": 15.00,
      "taxGroup": 2
    },
     {
      "text": "TEST_2",
      "quantity": 1,
      "unitPrice": 20.00,
      "taxGroup": 2
    }
   
  ],
  "payments": [
    
       
              {
      "amount": 20.00,
      
      "paymentType": "cash"
    }
     ,
              {
      "amount": -5.00,
      
      "paymentType": "change"
    },
       {
      "amount": 20.00,
      
      "paymentType": "card"
    }
       
    
  ]
}
RES:
{
    "receiptNumber": "",
    "receiptDateTime": "2019-08-27T12:01:51",
    "receiptAmount": 35,
    "fiscalMemorySerialNumber": "0XXXX",
    "ok": false,
    "messages": [
        {
            "type": "error",
            "code": "E199",
            "text": "General error"
        },
        {
            "type": "error",
            "code": "E404",
            "text": "The command is not allowed in the current fiscal mode"
        },
        {
            "type": "info",
            "text": "A fiscal receipt is open"
        },
        {
            "type": "info",
            "text": "SW7=OFF, SW6=OFF, SW5=OFF, SW4=OFF, SW3=OFF, SW2=OFF, SW1=OFF"
        },
        {
            "type": "info",
            "text": "Unique Printer ID and Fiscal Memory ID are set"
        },
        {
            "type": "info",
            "text": "BULSTAT UIC is set"
        },
        {
            "type": "info",
            "text": "The tax rates are set at least once"
        },
        {
            "type": "info",
            "text": "The printer is in fiscal mode"
        },
        {
            "type": "info",
            "text": "The fiscal memory is formatted"
        },
        {
            "type": "info",
            "text": "Error occurred while closing the receipt"
        },
        {
            "type": "info",
            "text": "Error occured while printing receipt items"
        }
    ]
}

--- WORKING REQUEST for Datecs
Tremol is working OK with that request as well
{
  "uniqueSaleNumber": "DT122222-0001-0000900",
  "items": [
    {
      "text": "TEST_1",
      "quantity": 1,
      "unitPrice": 15.00,
      "taxGroup": 2
    },
     {
      "text": "TEST_2",
      "quantity": 1,
      "unitPrice": 20.00,
      "taxGroup": 2
    }
   
  ],
  "payments": [
    
    
       {
      "amount": 20.00,
      
      "paymentType": "card"
    },
       
              {
      "amount": 20.00,
      
      "paymentType": "cash"
    }
     ,
              {
      "amount": -5.00,
      
      "paymentType": "change"
    }
       
    
  ]
}

RES:
{
    "receiptNumber": "0000090",
    "receiptDateTime": "2019-08-27T12:04:36",
    "receiptAmount": 35,
    "fiscalMemorySerialNumber": "0XXXXX",
    "ok": true,
    "messages": [
        {
            "type": "info",
            "text": "SW7=OFF, SW6=OFF, SW5=OFF, SW4=OFF, SW3=OFF, SW2=OFF, SW1=OFF"
        },
        {
            "type": "info",
            "text": "Unique Printer ID and Fiscal Memory ID are set"
        },
        {
            "type": "info",
            "text": "BULSTAT UIC is set"
        },
        {
            "type": "info",
            "text": "The tax rates are set at least once"
        },
        {
            "type": "info",
            "text": "The printer is in fiscal mode"
        },
        {
            "type": "info",
            "text": "The fiscal memory is formatted"
        }
    ]
}

The issue seems to be the placement of 'CARD' payment in the JSON Request.

**Comment by g-vvv** [comment]
Please provide debug.log

**Comment by dsetekh** [comment]
[debug.log](https://github.com/erpnet/ErpNet.FP/files/3545315/debug.log)

**Comment by g-vvv** [comment]
This debug log does not contain the problem. Maybe the problem is in the debug.log archives in the same folder, their names are in following format: debug.log.N.zip, N=1..9

**Comment by g-vvv** [comment]
When you use paymentType: "change", please check that you have enought money in the fiscal devices with /printers/printerId/cash, or if you have tracking of the money in the fiscal devices from your application. You need to have "change" money to give back to the customer.

**Comment by dsetekh** [comment]
[debug.log](https://github.com/erpnet/ErpNet.FP/files/3545819/debug.log)
Please, check this log, is not an issue of Cahs in / Out as one syntax ( cash in front ) is going thru and the other is not, it is an issue with Datecs protocol implementation.

**Comment by g-vvv** [comment]
Не всички плащания поддържат ресто.
Ползвайте рестото, само за изравняване на сумите, когато имате "безрестово" плащане. Безрестови плащания са например, талони, ваучъри, чекове.
В случая, в имплементацията на фърмуера на Датекс, според вашата бележка, той получава 20 лв кеш, после получава 20 лв. в карта и гърми там, защото не позволява да се вземе по карта по-голяма от оставащата сума. А това, че сме написали "paymentType":"change", "amount":5, е само декларативно за да може ErpNet.FP да даде възможност да се изчисли правилно сумата, за да провери, да не правите грешка при подаването на командата. Реално, не се подава никаква команда към ФУ, когато се използва "paymentType":"change". Това е само за да се позволи да се използват безрестови плащания, напремер идва клиент с ваучър за 40 лв, а сметката му е 35. Тогава ErpNet.FP ще му даде грешка, че сумата не съвпада, затова с  "paymentType":"change", "amount":5, ще дадете възможност да минете през тази проверка, като декларирате, че оставащите 5 лв. са ресто. Затварям този кейс.
