### ISSUE TITLE
Implementing all supported payments for all fiscal devices

### ISSUE THREAD

**Issue by g-vvv** [erpnet/ErpNet.FP#99]
- Implementing all supported payments for all fiscal devices.
- Returning of all supported payments for every fiscal device in /printers deviceInfo.

Our mapping definition:
    Our "paymentType" constant = NRA constant
---------------------------------------------------------
    "cash" = "SCash"
    "check" = "SChecks"
    "coupons" = "ST"
    "ext-coupons" = "SOT"
    "packaging" = "SP"
    "internal-usage" = "SSelf"
    "damage" = "SDmg"
    "card" = "SCards"
    "bank" = "SW"
    "reserved1" = "SR1"
    "reserved2" = "SR2

**Comment by g-vvv** [comment]
В брой, "cash", "SCash"
С чек, "check", "SChecks"
Талони, "coupons", "ST"
Външни талони, "ext-coupons", "SOT"
Амбалаж, "packaging", "SP"
Вътрешна употреба, "internal-usage", "SSelf"
Повреди, "damage", "SDmg"
Кредитни/дебитни карти, "card", "SCards"
Банкови трансфери, "bank", "SW"
Резерв 1/НЗОК "reserved1", "SR1"
Резерв 2 "reserved2", "SR2"

**Comment by wqweto** [comment]
Name                    | Code              | XML code
----                    | ----              | ----
В брой                  | `cash`            | `SCash`
С чек                   | `check`           | `SChecks`
Талони                  | `coupons`         | `ST`
Външни талони           | `ext-coupons`     | `SOT`
Амбалаж                 | `packaging`       | `SP`
Вътрешна употреба       | `internal-usage`  | `SSelf`
Повреди                 | `damage`          | `SDmg`
Кредитни/дебитни карти  | `card`            | `SCards`
Банкови трансфери       | `bank`            | `SW`
Резерв 1/НЗОК           | `reserved1`       | `SR1`
Резерв 2                | `reserved2`       | `SR2`
